options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: go-fiber-api
  _REGION: asia-southeast2
  _REPO_NAME: go-fiber
  _IMAGE_NAME: go-fiber-image
  _BRANCH_NAME: ${BRANCH_NAME}

steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['mod', 'download']
    dir: '.'

  - name: 'gcr.io/cloud-builders/go'
    args: ['test', './...']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$SHORT_SHA',
        '-f',
        'Dockerfile', 
        '.'
      ]
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
      ]
    dir: '.'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$_BRANCH_NAME" = "main" ]; then
          gcloud run deploy $_SERVICE_NAME \
            --image asia-southeast2-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$SHORT_SHA \
            --region $_REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-secrets ENV_VAR_1=projects/$PROJECT_ID/secrets/ENV_VAR_1:latest,ENV_VAR_2=projects/$PROJECT_ID/secrets/ENV_VAR_2:latest
        else
          echo "Not deploying because branch is not main."
        fi

images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
