name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo $GOOGLE_APPLICATION_CREDENTIALS > keyfile.json
        gcloud auth activate-service-account --key-file=keyfile.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml
